clear; close all; clc;

d = { ...
    'Brighton & Hove', 'Books', 610.00; ...
    'Brighton & Hove', 'Electronics', 855.00; ...
    'Brighton & Hove', 'Hardware', 998.00; ...
    'Brighton & Hove', 'Software', 2020.00; ...
    'Chichester', 'Home & Garden', 396.00; ...
    'Chichester', 'Health & Beauty', 580.00; ...
    'Chichester', 'Sports', 613.00; ...
    'Chichester', 'Software', 885.00; ...
    'Chichester', 'Electronics', 891.00; ...
    'Chichester', 'DIY', 1449.00; ...
    'Portsmouth', 'Books', 268.00; ...
    'Portsmouth', 'Home & Garden', 390.00; ...
    'Portsmouth', 'Electronics', 690.00; ...
    'Portsmouth', 'DIY', 834.00; ...
    'Portsmouth', 'Sports', 1008.00; ...
    'Portsmouth', 'Clothes', 1016.00; ...
    'Portsmouth', 'Toys & Children', 1201.00; ...
    'Southampton', 'DIY', 169.00; ...
    'Southampton', 'Hardware', 604.00; ...
    'Southampton', 'Electronics', 757.00; ...
    'Southampton', 'Sports', 1567.00; ...
    'Winchester', 'Hardware', 524.00; ...
    'Winchester', 'Sports', 541.00; ...
    'Winchester', 'Books', 806.00; ...
    'Winchester', 'Software', 991.00; ...
    'Winchester', 'Toys & Children', 1079.00; ...
    'Winchester', 'Electronics', 1661.00 ...
};

% Define super regions
super_region1 = {'Brighton & Hove', 'Chichester', 'Portsmouth'};
super_region2 = {'Southampton', 'Winchester'};

% Compute total revenue for branches
b = unique(d(:,1));
br = zeros(length(b),1);
for i = 1:length(b)
    br(i) = sum(cell2mat(d(strcmp(d(:,1), b{i}), 3)));
end

% Compute total revenue for super regions
super_region_revenue = [sum(br(ismember(b, super_region1))); sum(br(ismember(b, super_region2)))];

% Generate super region treemap layout
super_r = treemap(super_region_revenue / sum(super_region_revenue));

figure('Position', [100, 100, 1100, 850]);
hold on;

% Iterate over super regions
for sreg = 1:2
    if sreg == 1
        current_branches = super_region1;
    else
        current_branches = super_region2;
    end
    
    % Compute branch revenues for this super region
    reg_br = br(ismember(b, current_branches));
    
    % Compute branch treemap layout within the super region
    branch_r = treemap(reg_br / sum(reg_br), super_r(3,sreg), super_r(4,sreg));
    branch_r(1,:) = branch_r(1,:) + super_r(1,sreg);
    branch_r(2,:) = branch_r(2,:) + super_r(2,sreg);
    
    % Draw super region outline
    rectangle('Position', [super_r(1,sreg), super_r(2,sreg), super_r(3,sreg), super_r(4,sreg)], ...
              'EdgeColor', [0 0 0], 'LineWidth', 3, 'FaceColor', 'none');
    
    % Label super region
    text(super_r(1,sreg) + super_r(3,sreg)/2, super_r(2,sreg) + super_r(4,sreg) + 0.03, ...
         sprintf('Super Region %d', sreg), 'HorizontalAlignment', 'center', 'FontWeight', 'bold');
    
    % Draw branches inside super region
    for i = 1:length(current_branches)
        branch_idx = find(strcmp(b, current_branches{i}));
        branch_data = d(strcmp(d(:,1), current_branches{i}), :);
        products = unique(branch_data(:,2));
        product_revenue = zeros(length(products),1);
        
        for j = 1:length(products)
            product_revenue(j) = sum(cell2mat(branch_data(strcmp(branch_data(:,2), products{j}), 3)));
        end
        
        product_r = treemap(product_revenue / br(branch_idx), branch_r(3,i), branch_r(4,i));
        product_r(1,:) = product_r(1,:) + branch_r(1,i);
        product_r(2,:) = product_r(2,:) + branch_r(2,i);
        
        % Draw branch outline
        rectangle('Position', [branch_r(1,i), branch_r(2,i), branch_r(3,i), branch_r(4,i)], ...
                  'EdgeColor', 'k', 'LineWidth', 1.5);
        
        % Draw product rectangles
        for k = 1:length(products)
            rectangle('Position', [product_r(1,k), product_r(2,k), product_r(3,k), product_r(4,k)], ...
                      'FaceColor', rand(1,3), 'EdgeColor', 'w');
        end
        
        % Branch label
        text(branch_r(1,i) + branch_r(3,i)/2, branch_r(2,i) + branch_r(4,i) + 0.01, ...
             current_branches{i}, 'HorizontalAlignment', 'center', 'FontWeight', 'bold');
    end
end
hold off;
